config/routes.rb
Basnioteka::Application.routes.draw do

  resources :illustrations

  resources :comments

  resources :authors
  resources :heros do
    get :autocomplete_story_title, :on => :collection
  end

  resources :stories
  resources :users
  resource :user_session, :only => [:new, :create, :destroy]
  
  
  match "login" => "user_sessions#new"
  
  match "logout" => "user_sessions#destroy"
  match "home"=>"static_pages#home"
  match "about"=>"static_pages#about"
  root :to => 'static_pages#home'

end

app/models/hero.rb
#encoding: utf-8
class Hero < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  has_many :comments
  has_many :illustrations
  acts_as_taggable
  acts_as_taggable_on :tags
scope :by_letter,
	lambda { |letter| {
	:conditions => ["heros.name LIKE ?", "#{letter}%"]
}}
  def story_title
    story.title if story
  end
  def story_title=(title)
    self.story = Story.find_or_create_by_title(title) unless title.blank?
  end
  validates :name,  :presence => {:message => 'Musisz podać nazwę lub imię postaci.'}
  validates :name, :uniqueness => { :scope => :story_id, :message =>'Taka postać już została opisana w obrębie tej baśni.' }

  validates :description, 
    :length => {:minimum => 150, :too_short => 'Opis postaci musi zawierać minimum 150 znaków - jedno dobre zdanie.' }
  tag_format = /^\s*[A-Za-z0-9\sąĄćĆĘęńŃóÓŚśżŻźŹłŁ]+(\s*,\s*[A-Za-z0-9\sąĄćĆŃńęĘóśŚÓłŁżŻźŹ]+)*\s*$/i

  validates :tag_list, 
    :format =>{:with => tag_format, :message => "Poszczególne tagi odzielaj przecinkami. Dozwolone znaki dla tagów to litery, cyfry oraz spacje."} 

  validates :story_id,  :presence => {:message => 'Musisz wybrać baśń.'}
  mount_uploader :picture, PictureUploader
end

app/controllers/heros_controller.rb
#encoding:utf-8
class HerosController < ApplicationController
  # GET /heros
  # GET /heros.json
  before_filter :find_stories, :only => [:new, :edit, :update, :create]
  before_filter :authenticate, :except => [:index, :show]
  autocomplete :story, :title
  @tags = Hero.tag_counts_on(:tags)
  def index
	@all_heros = Hero.all.group_by { |h| h.name[0].upcase }
    if params[:tag_name]
      @heros = Hero.tagged_with(params[:tag_name]).group_by{ |h| h.name[0].upcase}
    elsif params[:letter]
      @heros = Hero.by_letter(params[:letter]).group_by{ |h| h.name[0].upcase}
    else
      @heros = Hero.all.group_by{ |h| h.name[0].upcase}
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @heros }
    end
  end

    # GET /heros/1
    # GET /heros/1.json
    def show
      @hero = Hero.find(params[:id])
      @story=Story.find(@hero.story_id)
      @authors=@story.authors
      @comments = @hero.comments
      @comment = Comment.new
      @illustrations = @hero.illustrations
      @illustration = Illustration.new
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @hero }
      end
    end

    # GET /heros/new
    # GET /heros/new.json
    def new
      @hero = Hero.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @hero }
      end
    end

    # GET /heros/1/edit
    def edit
      @hero = Hero.find(params[:id])
    end

    # POST /heros
    # POST /heros.json
    def create
      @hero = Hero.new(params[:hero])
      @hero.user = current_user
        if @hero.save
         redirect_to @hero, notice: 'Nowy bohater został utworzony.'
        else
        render action: "new"
        end
    end

    # PUT /heros/1
    # PUT /heros/1.json
    def update
      @hero = Hero.find(params[:id])

      respond_to do |format|
        if @hero.update_attributes(params[:hero])
          format.html { redirect_to @hero, notice: 'Bohater został zaktualizowany.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @hero.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /heros/1
    # DELETE /heros/1.json
    def destroy
      @hero = Hero.find(params[:id])
      @hero.destroy

      respond_to do |format|
        format.html { redirect_to heros_url }
        format.json { head :no_content }
      end
    end
    protected
    def find_stories
    @stories = Story.all.sort_by{|s| s.title}
      @stories =@stories.map do |story|
        [story.title, story.id]
      end
    end
  end

app/helpers/heros_helper.rb
module HerosHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/heros/_authors_fields.html.erb
<p>


    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
    <%= f.check_box :_destroy %>
    <%= f.label :_destroy, "Remove" %>   
 </p>

app/views/heros/_form.html.erb
<%= form_for @hero, :html => {:multipart => true}, :validate=> true do |f| %>
  <%= f.error_messages %>
    <%= f.label "nazwa" %><br />
    <%= f.text_field :name %>
  <div class="field">
    <%= f.label :story_id, "baśńooo" %><br />
    <%= f.select :story_id, @stories %>
  </div>
  <div class="field">
    <%= f.label "opis" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "ilustracja" %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label "opis ilustracji:" %><br />
    <%= f.text_field :image_description %>
  </div>
  <div class="field">
    <%= f.label "tagi" %><br />
    <%= f.text_field :tag_list, :value=>@hero.tag_list %>
  </div>

app/views/heros/_stories_fields.html.erb
<p>
  <%= f.label :title, "Story" %><br />
  <%= f.text_area :title%><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Story" %>
  </p>

app/views/heros/edit.html.erb
<h1>Edycja bohatera</h1>
<div class="edithero">
<%= image_tag('castleupedit.png', :class=>"castle") %>
<%= form_for @hero, :html => {:multipart => true}, :validate=> true do |f| %>
  <%= f.error_messages %>
  <div class="field">
  <span>*</span>  <%= f.label "nazwa" %><br />
  <%= f.text_field :name %>
</div>
  <div class="field">
    <span>*</span> <%= f.label :story_id, "Baśń" %><br />
    <%= f.select :story_id, @stories %>
  </div>
  <div class="field">
    <span>*</span> <%= f.label "opis" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <span>*</span> <%= f.label "tagi" %><br />
    <%= f.text_field :tag_list, :value=>@hero.tag_list %>
  </div>
  <div class="field">
    <%= f.label "ilustracja" %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label "opis ilustracji:" %><br />
    <%= f.text_field :image_description %>
  </div>
  <div class="actions">
    <%= f.submit "", :class=> 'buttonedithero'%>
  </div>
<% end %>
</div>
<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heros/index.html.erb
<div class='matop'></div>
<div class='main'>
<div class='literki'>
  <% @all_heros.keys.sort.each do |starting_letter| %>
	<% if params[:letter] == starting_letter %>
	<b><span> <%= starting_letter %> </span>|</b>
	<%else%>
  <b><%= link_to starting_letter, heros_path(:letter => starting_letter)%>|</b>
	<% end %>
  <% end %>
</div>
<%= image_tag('pasek.png', :class=>'pasek') %>
	<% if params[:tag_name] %>
		<div class="tagged">Bohaterowie otagowani jako <span><%= params[:tag_name]%></span></div>
	<%end%>
<ol>
	<ul>
<% @heros.keys.sort.each do |starting_letter| %>
  <div class="oneletter">
	 <li class="letter"> <%= starting_letter %></li>
	<ul>
  <% @heros[starting_letter].each do |hero| %>
  <li>  <%= link_to hero.name, hero %>
         <% story = Story.find(hero.story_id) %>
         <i>(<%= story.title %>)</i></li>
  <% end%>
</ul>
</div>
<% end %>
</ul>
</ol>
</div>
<div class='mabottom'></div>

app/views/heros/new.html.erb
<h1>Dodaj bohatera</h1>
<div class="form_newhero">
<%= image_tag('castleup.png', :class=>"castle") %>
<%= form_for @hero, :html => {:multipart => true}, :validate=> true do |f| %>
  <%= f.error_messages %>
  <div class="field">
  <span>*</span> <%= f.label "nazwa" %><br />
  <%= f.text_field :name %>
</div>
  <div class="field">
    <span>*</span> <%= f.label "Baśń" %></br>
    <%= f.select :story_id, @stories, {:include_blank => true} %>
  </div>
  <div class="field">
    <span>*</span> <%= f.label "opis" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
  <span>*</span> <%= f.label "tagi" %><br />
    <%= f.text_field :tag_list, :value=>@hero.tag_list %>
  </div>
  <div class="field">
    <%= f.label "ilustracja" %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label "opis ilustracji:" %><br />
    <%= f.text_field :image_description %>
  </div>
  <div class="actions">
    <%= f.submit "", :class=> 'buttonnewhero'%>
  </div>
<% end %>
</div>
<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heros/show.html.erb
<div class="matop"></div>
<div class="main">
  <p id="notice"><%= notice %></p>
  <div class ="picture">
    <%= image_tag(@hero.picture_url(:thumb), :class=>"picture")  %>
    <%= @hero.image_description %>
  </div>
  <div class="textbox">
    <h2>
      <%= @hero.name %>
    </h2>
    <h4>
      z baśni: <i><%= link_to @hero.story.title, story_path(@story) %></i>
      
      napisanej przez:
      <% @authors.each do |a| %>
        <i>  <%= link_to a.first_name + ' ' + a.last_name, author_path(a) %></i> |
      <% end %>
    </h4>
    <div class="info">
      dodane przez <%= link_to @hero.user.login, user_path(@hero.user), :class=>'user' %>
    tagi:
    <% @hero.tags.each do |tag| %>
      <%= link_to tag.name, heros_path(:tag_name => tag.name), :class=> 'tag' %>
    <%end%>
  </div>
  <hr>
  <%= @hero.description.html_safe %>


</div>
  <div class="opcje3">
<% if current_user %>
    <% if (current_user.id==@hero.user_id) || (current_user.admin ==true)%>
      <%= link_to 'Edytuj', edit_hero_path(@hero) %> 
      <%= link_to 'Usuń', @hero, confirm: 'Jesteś pewien, że chcesz usunąć tego bohatera?', method: :delete %>
    <%end%>
<% end %>
  </div>
<div class='illcom'> 
  <div class="flipcomments"><%= image_tag('buttonflipcomments.png')%></div>
  <div class="flipillustrations"><%=image_tag('buttonflipillustrations.png')%> </div>
</div>
</div>
<%= image_tag('mainbottom.png', :class=>'mainbottom2') %>


<div class="comments">

  <% unless current_user %>
    <p id="notice">	Aby dodawać komentarze musisz być zalogowany.</p>
  <% end %>
  <% if @hero.comments.empty?%>
    <h4> Ten bohater nie ma jeszcze komentarzy </h4>
  <% end %>
  <% unless @hero.comments.empty? %>
    <% @hero.comments.each do |comment| %>
      <%= comment.created_at.strftime("%Y-%m-%d %H:%M") %>
      <strong><%= link_to comment.user_name, user_path(@user_id) %></strong>napisał(a):
         <% if defined?(current_user.login) && ((current_user.login== comment.user_name) || (current_user.admin == true)) %>
               |<%= link_to 'Usuń', comment, confirm: 'Jesteś pewny, że chcesz usunąć ten komentarz?', method: :delete %>
         <% end %>
  <br />
  <div class="comment">
    <%= comment.body %>
  </div>
<% end %>
<% end %>
<% if current_user %>
<%= render 'comments/form' %>
<% end %>


<div class='upcom'> 
  <div class="flipcomments"><%= image_tag('flipcomup.png', :class=>"comup")%></div>
</div>
<%= image_tag('commbottom.png', :class => 'commbottom' )%>
</div>

<div class='illustrations'>
  <% if @hero.illustrations.empty? %>
    <h4> Ten bohater nie ma jeszcze ilustracji </h4>
  <% end %>
  <% @hero.illustrations.each do |illustration| %>
    <div class= "ilustracja">
    <a href="<%= illustration.illustration_url(:big)%>" title="Dodane przez: <%= illustration.user_name%>. Opis: <%= illustration.description%>" rel="lightbox[ills]">
      <%= image_tag(illustration.illustration_url(:thumb)) if illustration.illustration?  %>
    </a>
    <% if current_user && ((current_user.login==illustration.user_name) || (current_user.admin == true)) %>
      <%= link_to 'Usuń', illustration, :class=>"fotousuwanie",confirm: 'Jesteś pewny, że chcesz usunąć to zdjęcie?', method: :delete %>
    <% end %>
  </div>
  <% end %>
  <% if current_user %>
    <%= render 'illustrations/form' %>
  <% else %>
    <h4> Aby dodawać ilustracje musisz być zalogowany. </h4>    
  <% end %>
  <div class='upill'> 
    <div class="flipillustrations"><%=image_tag('flipillup.png')%></div>
  </div>
  <%= image_tag('illbottom.png', :class => 'illbottom') %>
</div>