config/routes.rb
Basnioteka::Application.routes.draw do

  resources :illustrations

  resources :comments

  resources :authors
  resources :heros do
    get :autocomplete_story_title, :on => :collection
  end

  resources :stories
  resources :users
  resource :user_session, :only => [:new, :create, :destroy]
  
  
  match "login" => "user_sessions#new"
  
  match "logout" => "user_sessions#destroy"
  match "home"=>"static_pages#home"
  match "about"=>"static_pages#about"
  root :to => 'static_pages#home'

end

app/models/story.rb
#encoding: UTF-8
class Story < ActiveRecord::Base
  has_many :heros,:order =>'name ASC' , :dependent => :destroy
  has_and_belongs_to_many :authors
 
  validates :title, :uniqueness => { :message => 'Jest już taka baśń' }
  validates :title,  :presence => {:message => 'Musisz podać tytuł.'}
  validates :authors,  :presence => {:message => 'Musisz podać autora.'}
  #validates :author_id,  :presence => {:message => 'Musisz podać autora.'}





end

app/controllers/stories_controller.rb
#encoding: UTF-8
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json

  before_filter :find_authors, :only => [:new, :edit, :update, :create]
  before_filter :authenticate, :except => [:index, :show]
  def index
    @stories = Story.all.sort_by{|s| s.title}
    @all_stories = Story.all.group_by { |h| h.title[0].upcase }
    @stories_by_letter = @stories.group_by{ |s| s.title.first.upcase}.sort

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])
    
 #  @author=Author.find(@story.author_id)
   @heros = @story.heros
   @heros_by_letter= @heros.group_by{ |n| n.name.first.upcase}.sort


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
    @story.title.capitalize!
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])
    @story.title[0]=@story.title[0].capitalize

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Nowa baśń została dodana.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])
    

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Zmiany zostały zapisane.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end
  protected
    def find_authors
        @authors = Author.find(:all).map do |author|
          [author.first_name + ' ' + author.last_name, author.id]
        end
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for @story, :validate => true do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label "Tytuł" %><br/>
    <%= f.text_field :title %>
  </div>
	<% f.fields_for :authors do |a| %>
		<%= p.label_for :author_id %>
		<%= p.select :author_id, @authors, {:include_blank => true } %>
	<% end %>
  <div class="field">
    <%= f.label :author_id %>
    <%= f.select :author_id, @authors, {:include_blank => true} %>
    <%= f.select :author_id, @authors, {:include_blank => true} %>
  </div>
  <div class="field">
    <%= f.label "opis" %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Edycja baśni</h1>

<div class="formstory2">
<%= form_for @story, :validate => true do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <span>*</span>  <%= f.label "Tytuł" %><br/>
    <%= f.text_field :title %>
  </div>
    <%#= f.select :author_id, @authors, {:include_blank => true} %>
    <div class="field">
      <% for author in Author.all %>
        <%= check_box_tag "story[author_ids][]", author.id, @story.authors.include?(author) %>
        <%= author.full_name %> <br />       
      <% end %>
    </div>
  <div class="field">
    <%= f.label "opis" %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "", :class=>"buttoneditstory" %>
  </div>
<% end %>
</div>

app/views/stories/index.html.erb
<div class="matop"></div>
<div class="main">
  <ol class="story">
    <ul>
      <% @stories_by_letter.each do |letter, stories| %>
        <div class="oneletter">
          <li class="letter"><%= letter %></li>
          <ul>
            <% stories.sort_by(&:title).each do |story| %>
  
              <li><%=link_to story.title, story %>|
                    <%  @authors=story.authors %>
                    <%= @authors.map(&:full_name).join(', ')%>
              
             <% end %>
           </ul>
         </div>
       <%end %>
  
    </ul>
  </ol>

<%= link_to 'Dodaj nową baśń', new_story_path %>
</div>
<div class="mabottom"></div>

app/views/stories/new.html.erb
<h1>Nowa baśń</h1>
<div class="formstory">
  <%= form_for @story, :validate => true do |f| %>
    <%= f.error_messages %>
    <div class="field">
      <span>*</span>   <%= f.label "Tytuł" %><br/>
      <%= f.text_field :title %>
    </div>
    <%# f.fields_for :authors do |a| %>
      <%#= p.label_for :author_id %>
      <%#= p.select :author_id, @authors, {:include_blank => true } %>
      <%# end %>
      <div class="field">
        <span>*</span>Autorzy <br />
      <% for author in Author.all %>
        <%= check_box_tag "story[author_ids][]", author.id, @story.authors.include?(author) %>
        <%= author.full_name %> <br />      
      <% end %>
    </div>
    <div class="field">
      <%= f.label "opis" %>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.submit "", :class=>"buttonnewstory" %>
    </div>
  <% end %>
</div>

app/views/stories/show.html.erb
<div class="matop"></div>
<div class="main">
  <p id="notice"><%= notice %></p>

  <h3><i><%= @story.title %></i></h3>
  <div class="autorstwa">
    <b>Autorstwa:</b>
    <% @story.authors.each do |a| %>
      <%= link_to a.full_name, author_path(a) %> |
      
    <% end %>
  </div>
  <%= @story.description.html_safe%>
<div class="opcje"> 
<%if current_user %> 
  <%= link_to 'Edytuj', edit_story_path(@story) %>
<% if current_user.admin == true %>
  <%= link_to 'Usuń', @story, confirm: 'Jesteś pewien, że chcesz usunąć tę baśń?', method: :delete %>
<% end %>
<% end %>
  </div>
  <hr>
  <% unless @heros.empty? %>
    <h4> Postacie opisane z tej baśni: </h4> 
    <ol class="story">
      <ul>
        <% @heros_by_letter.each do |letter, heros| %>
          <div class="oneletter">
            <li class="letter"><%= letter %> </li>
            <ul>
              <% heros.sort_by(&:name).each do |hero|%>
                <li><%= link_to hero.name, hero_path(hero)%></li>
              <% end%>
            </ul>
          </div>
        <% end %>
      </ul>
    </ol>
  <% else %>
    <h4> Postacie z tej baśni nie zostały jeszcze opisane. </h4>
  <% end %>

</div>
<div class="mabottom"></div>