config/routes.rb
Basnioteka::Application.routes.draw do

  resources :illustrations

  resources :comments

  resources :authors
  resources :heros do
    get :autocomplete_story_title, :on => :collection
  end

  resources :stories
  resources :users
  resource :user_session, :only => [:new, :create, :destroy]
  
  
  match "login" => "user_sessions#new"
  
  match "logout" => "user_sessions#destroy"
  match "home"=>"static_pages#home"
  match "about"=>"static_pages#about"
  root :to => 'static_pages#home'

end

app/views/layouts/about.html.erb
<html>
  <head>
    <title>Baśnioteka - katalog postaci baśniowych</title>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Patrick+Hand&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag "application","special","lightbox", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "jquery-1.7.2.min.js"%>
    <%= javascript_include_tag "lightbox.js"%>
  </head>
  <body>
    <div class="wrap">
      <div class=home>
        <%= image_tag('logo.png', :class=>"basnikon")%>
        <h5> Katalog postaci baśniowych </h5>
      </div>
      <div class="about">
        Baśnikon to projekt dyplomowy przygotowany pod kierunkiem prof. dra hab. Grzegorza Bilińskiego.<br />
        WZiKS UJ, kierunek: kulturoznawstwo, specjalność: elektroniczne przetwarzanie informacji.<br />
        Projekt zrealizowała Małgorzata Nowak lubie.pracowac@gmail.com<br />
        Kraków 2012
        <h5><%=link_to "&#8592  powrót".html_safe, home_path %> </h5>
      </div>
      <footer>
        <p>Małgorzata Nowak &#169 <%= Time.now.year %><br />
           <%=link_to "o stronie", about_path%>
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baśnioteka - katalog postaci baśniowych</title>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Patrick+Hand&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "authors", :media => "all" %>
    <%= stylesheet_link_tag "users", :media => "all" %>
    <%= stylesheet_link_tag "heros", :media => "all" %>
    <%= stylesheet_link_tag "stories", :media => "all" %>
    <%= stylesheet_link_tag "lightbox", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "autocomplete-rails.js" %>
    <%= javascript_include_tag "jquery-1.7.2.min.js"%>
    <%= javascript_include_tag "lightbox.js"%>
  </head>
  <body>
    <div class="wrap">
    <header>
        <% if current_user %>
      <div class="miniprofil">
      <div class="border">
        <p>Witaj, <%=link_to current_user.login, current_user, :title=>"twój profil"%>!<p>
        <div class="submenu">
        <ul>
          <li><%= link_to 'dodaj bohatera', new_hero_path, :title=>"dodaj bohatera" %></li>
          <li><%= link_to "dodaj baśń", new_story_path, :title=>"dodaj baśń" %></li>
          <li><%= link_to 'dodaj autora', new_author_path, :title=>"dodaj autora" %></li>
          <li><%= link_to "wyloguj się", logout_path, :title=>"wyloguj się" %></li>
        </ul>
        </div>
     </div>
     </div>
    <% else %>
  <%= link_to  "<div class='minilogowanie'>
        </div>".html_safe, login_path, :title=>"zaloguj się" %>
    <% end %>
    <% unless current_user %>
      <%= link_to image_tag('register.png',:class=>'register'), new_user_path, :title=>"zarejestruj się" %>
    <% end %>
  <div class="top">
    <div class="topcontainer">



      <nav>
      <ul class=menu>
        <%= link_to "<li class='logo'></li>".html_safe, root_url, :title=>"strona główna" %>
        <li class="hero"><p><%= link_to "bohaterowie", heros_path, :title=>"bohaterowie" %></p></li>
        <li class="story"><p><%= link_to  "baśnie", stories_path, :title=>"baśnie"%></p></li>
        <li class="author"><p><%= link_to "autorzy", authors_path, :title=>"autorzy"%></p></li>
      </ul>
      </nav>
    </div>
  </div>
  </header>
  <div class=wrapper>
      <%= yield %>
  </div>
  <footer>
        <p>Małgorzata Nowak &#169 <%= Time.now.year %><br />
        <%=link_to "o stronie", about_path, :title=>"o stronie"%>
        </p>
  </footer>
</div>
</body>
</html>

app/views/layouts/special.html.erb
<html>
  <head>
    <title>Baśnioteka - katalog postaci baśniowych</title>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Patrick+Hand&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag "application","special","lightbox", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "jquery-1.7.2.min.js"%>
    <%= javascript_include_tag "lightbox.js"%>
  </head>
  <body>
    <div class="wrap">
      <div class=home>
        <%= image_tag('logo.png', :class=>"basnikon")%>
        <h5> Katalog postaci baśniowych </h5>
        <h6> przeglądaj:</h6>
        <%= link_to image_tag("homeregister.png", :class=>"homeregister"), new_user_path %>
        <%= link_to image_tag("homelogin.png", :class=>"homelogin"), login_path %>
      </div>
      <div class="homemenu">
        <%= link_to image_tag("homeheros.png", :class=>"homemenuill"), heros_path %>
        <%= link_to image_tag("homestories.png", :class=>"homemenuill"), stories_path %>
        <%= link_to image_tag("homeauthors.png", :class=>"homemenuill"), authors_path %>
      </div>
      <footer>
        <p>Małgorzata Nowak &#169 <%= Time.now.year %><br />
           <%=link_to "o stronie", about_path%>
        </p>
      </footer>
    </div>
  </body>
</html>